// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvaD--JDIqIsao1NNxwCOHrQm3n64dunU',
    appId: '1:118026964260:web:6e35c12696d91f55f0b7b1',
    messagingSenderId: '118026964260',
    projectId: 'pawradise-4e975',
    authDomain: 'pawradise-4e975.firebaseapp.com',
    storageBucket: 'pawradise-4e975.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg8bzynbVhqyHkHr6b4YWmapusXUS4gbI',
    appId: '1:118026964260:android:2cbaf1caaaea94e5f0b7b1',
    messagingSenderId: '118026964260',
    projectId: 'pawradise-4e975',
    storageBucket: 'pawradise-4e975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ENdUwVuVVGglUErdIrJFRhnaVz2H4oM',
    appId: '1:118026964260:ios:45705fd72702e4ccf0b7b1',
    messagingSenderId: '118026964260',
    projectId: 'pawradise-4e975',
    storageBucket: 'pawradise-4e975.firebasestorage.app',
    iosBundleId: 'com.example.pawradise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ENdUwVuVVGglUErdIrJFRhnaVz2H4oM',
    appId: '1:118026964260:ios:45705fd72702e4ccf0b7b1',
    messagingSenderId: '118026964260',
    projectId: 'pawradise-4e975',
    storageBucket: 'pawradise-4e975.firebasestorage.app',
    iosBundleId: 'com.example.pawradise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvaD--JDIqIsao1NNxwCOHrQm3n64dunU',
    appId: '1:118026964260:web:501c816026fc4373f0b7b1',
    messagingSenderId: '118026964260',
    projectId: 'pawradise-4e975',
    authDomain: 'pawradise-4e975.firebaseapp.com',
    storageBucket: 'pawradise-4e975.firebasestorage.app',
  );
}
